# -- repository yaml --

# Explicitly wait for all jobs to finish, as wait_for_ci prematurely triggers.
# See https://github.com/python-trio/trio/issues/2689
codecov:
  notify:
    # This number needs to be changed whenever the number of runs in CI is changed.
    # Another option is codecov-cli: https://github.com/codecov/codecov-cli#send-notifications
    after_n_builds: 78
    wait_for_ci: false
    notify_error: true # if uploads fail, replace cov comment with a comment with errors.
  require_ci_to_pass: false

# only post PR comment if coverage changes
comment:
  require_changes: true

coverage:
  # required range
  range: 99.6..100
  status:
    # require patches to be 100%
    patch:
      default:
        target: 100%
