# https://docs.readthedocs.io/en/latest/config-file/index.html
version: 2

formats:
  - htmlzip
  - epub

build:
  os: "ubuntu-22.04"
  tools:
    # make sure that this matches the intersphinx inventory we use for Python
    python: "3.11"

python:
  install:
    - requirements: docs-requirements.txt

sphinx:
  fail_on_warning: true
