# https://docs.readthedocs.io/en/latest/config-file/index.html
version: 2

formats:
  - htmlzip
  - epub

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - requirements: docs-requirements.txt
    - path: .

sphinx:
  fail_on_warning: true
  configuration: docs/source/conf.py
